# Project Title: IMDB Movie Recommendation System Using Storylines

## _Approaches of the project_
---
## TASK 1:- Data Scraping and Storage:

* Data Source: IIMDb 2024 Movies page (link).
* Scraping Method: Use Selenium to extract the following data:
    - Movie Name
    - Storyline (Plot Summary)
* Data Storage: Save the extracted movie data into a CSV file for further analysis.
    - Columns:
    - Movie Name
    - Storyline
* CSV Storage: Save the data in a CSV format for easy data manipulation.

### Import required packages
***

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import time

### Scraping the data from the IMPd Library URL
---

   * Load the driver for the browser where we want to open the url.
   * Get the url.
   * We have to write the code for the options what should be done there for downloading.
        - Search opetion
        - Button Click option if any
        - Copy the text from the proper class name/ID
        - Save it in a file.
        - Close the browser

In [6]:
# driver = webdriver.Chrome()

In [10]:
# url = "https://www.imdb.com/search/title/?year=2024"
# driver.get(url)
# time.sleep(3)

In [11]:
# movies = []
# movie_links = driver.find_elements(By.XPATH, "//h3[@class='lister-item-header']/a")

In [12]:
# for link in movie_links:
    # movie_name = link.text
    # movie_url = link.get_attribute("href")
    
    # driver.get(movie_url)
    # time.sleep(2)
    
    # try:
        # storyline = driver.find_element(By.XPATH, "//span[@data-testid='plot-xl']").text
    # except:
        # storyline = "Not Available"
    
    # movies.append([movie_name, storyline])
    # driver.back()
    # time.sleep(2)"""

In [13]:
# df = pd.DataFrame(movies, columns=["Movie Name", "Storyline"])
# df.to_csv("imdb_2024_movies.csv", index=False)

# driver.quit()

In [5]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import time

driver = webdriver.Chrome()
wait = WebDriverWait(driver, 300)

driver.get("https://www.imdb.com/search/title/?year=2024")

movies = []
collected_count = 0

while True:

    wait.until(EC.presence_of_all_elements_located(
        (By.CLASS_NAME, "ipc-metadata-list-summary-item")
    ))

    movie_cards = driver.find_elements(
        By.CLASS_NAME, "ipc-metadata-list-summary-item"
    )

    total_on_page = len(movie_cards)
    print(f"Currently loaded: {total_on_page}")

    # Collect only newly added cards
    for card in movie_cards[collected_count:]:
        try:
            title = card.find_element(By.CLASS_NAME, "ipc-title__text").text
        except:
            title = "Not Available"

        try:
            storyline = card.find_element(By.CLASS_NAME, "ipc-html-content-inner-div").text
        except:
            storyline = "Not Available"

        movies.append([title, storyline])

    collected_count = total_on_page

    # Try clicking 50 more
    try:
        button = driver.find_element(
            By.XPATH,
            "//button[.//span[contains(text(),'50 more')]]"
        )

        driver.execute_script("arguments[0].scrollIntoView();", button)
        time.sleep(2)

        driver.execute_script("arguments[0].click();", button)

        # Wait until new cards are added
        wait.until(lambda d: len(
            d.find_elements(By.CLASS_NAME, "ipc-metadata-list-summary-item")
        ) > total_on_page)

        time.sleep(2)

    except:
        print("No more 50 more button.")
        break

df = pd.DataFrame(movies, columns=["Movie Name", "Storyline"])
df.to_csv("imdb_2024_movies.csv", index=False)
df.to_csv("imdb_2024_movies.txt", index=False, sep="\t")

driver.quit()

print(f"Scraping completed. Total movies collected: {len(movies)}")

Currently loaded: 50
Currently loaded: 100
Currently loaded: 150
Currently loaded: 200
Currently loaded: 250
Currently loaded: 300
Currently loaded: 350
Currently loaded: 400
Currently loaded: 450
Currently loaded: 500
Currently loaded: 550
Currently loaded: 600
Currently loaded: 650
Currently loaded: 700
Currently loaded: 750
Currently loaded: 800
Currently loaded: 850
Currently loaded: 900
Currently loaded: 950
Currently loaded: 1000
Currently loaded: 1050
Currently loaded: 1100
Currently loaded: 1150
Currently loaded: 1200
Currently loaded: 1250
Currently loaded: 1300
Currently loaded: 1350
Currently loaded: 1400
Currently loaded: 1450
Currently loaded: 1500
Currently loaded: 1550
Currently loaded: 1600
Currently loaded: 1650
Currently loaded: 1700
Currently loaded: 1750
Currently loaded: 1800
Currently loaded: 1850
Currently loaded: 1900
Currently loaded: 1950
Currently loaded: 2000
Currently loaded: 2050
Currently loaded: 2100
Currently loaded: 2150
Currently loaded: 2200
Currently loaded: 2250
Currently loaded: 2300
Currently loaded: 2350
Currently loaded: 2400
Currently loaded: 2450
Currently loaded: 2500
Currently loaded: 2550
Currently loaded: 2600
Currently loaded: 2650
Currently loaded: 2700
Currently loaded: 2750
Currently loaded: 2800
Currently loaded: 2850
Currently loaded: 2900
Currently loaded: 2950
Currently loaded: 3000
Currently loaded: 3050
Currently loaded: 3100
Currently loaded: 3150
Currently loaded: 3200
Currently loaded: 3250
Currently loaded: 3300
Currently loaded: 3350
Currently loaded: 3400
Currently loaded: 3450
Currently loaded: 3500
Currently loaded: 3550
Currently loaded: 3600
Currently loaded: 3650
Currently loaded: 3700
Currently loaded: 3750
Currently loaded: 3800
Currently loaded: 3850
Currently loaded: 3900
Currently loaded: 3950
Currently loaded: 4000
Currently loaded: 4050
Currently loaded: 4100
Currently loaded: 4150
Currently loaded: 4200
Currently loaded: 4250
Currently loaded: 4300
Currently loaded: 4350
Currently loaded: 4400
Currently loaded: 4450
Currently loaded: 4500
Currently loaded: 4550
Currently loaded: 4600
Currently loaded: 4650
Currently loaded: 4700
Currently loaded: 4750
Currently loaded: 4800
Currently loaded: 4850
Currently loaded: 4900
Currently loaded: 4950
Currently loaded: 5000
Currently loaded: 5050
Currently loaded: 5100
Currently loaded: 5150
Currently loaded: 5200
Currently loaded: 5250
Currently loaded: 5300
Currently loaded: 5350
Currently loaded: 5400
Currently loaded: 5450
Currently loaded: 5500
Currently loaded: 5550
Currently loaded: 5600
Currently loaded: 5650
Currently loaded: 5700
Currently loaded: 5750
Currently loaded: 5800
Currently loaded: 5850
Currently loaded: 5900
Currently loaded: 5950
Currently loaded: 6000
Currently loaded: 6050
Currently loaded: 6100
Currently loaded: 6150
Currently loaded: 6200
Currently loaded: 6250
Currently loaded: 6300
Currently loaded: 6350
Currently loaded: 6400
Currently loaded: 6450
No more 50 more button.
Scraping completed. Total movies collected: 6450

### Hence the Task 1 has been completed successfully.

## TASK 2: Data Preprocessing and Analysis:
---
* Text Cleaning (NLP):
    - Preprocess the storyline text by removing stop words, punctuation, and unnecessary characters.
    - Tokenize the story text for further analysis.
* Text Representation:
    - Use TF-IDF Vectorizer or Count Vectorizer to convert the movie storylines into numerical vectors.
* Cosine Similarity:
    - Calculate the Cosine Similarity between the movie storylines to find the most similar movies.
    - Rank the movies based on similarity scores.

### Import required packages

In [57]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [17]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\koushik\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [18]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\koushik\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [19]:
stop_words = set(stopwords.words('english'))

### Load the scraped data

In [36]:
df = pd.read_csv("imdb_2024_movies.txt", sep="\t")

In [37]:
df

,Movie Name,Storyline
0,1. Fallout,"In a future, post-apocalyptic Los Angeles brou..."
1,2. Cross,Series adaptation of James Patterson novels ab...
2,3. Landman,A modern-day tale of fortune seeking in the wo...
3,4. High Potential,A single mom with three kids helps solve an un...
4,5. The Substance,A fading celebrity takes a black-market drug: ...
...,...,...
6445,6446. Rob N Roll,Decadent Murong Hui teams up with violent band...
6446,6447. Buttons,A straight and narrow man must find a way to l...
6447,6448. Mecha-Ude: Mechanical Arms,Middle schooler Hikaru partners with rare Mech...
6448,6449. Idiyan Chandhu,"Chandu, a young boy whose formative years were..."
6449,6450. TheWeekend,"Jonathan Capehart, Eugene Daniels and Jackie A..."

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6450 entries, 0 to 6449
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Movie Name  6450 non-null   object
 1   Storyline   6450 non-null   object
dtypes: object(2)
memory usage: 100.9+ KB

In [39]:
df.isnull().value_counts()

Movie Name  Storyline
False       False        6450
Name: count, dtype: int64

In [40]:
df.describe()

              Movie Name      Storyline
count               6450           6450
unique              6450           6178
top     6450. TheWeekend  Not Available
freq                   1            272

In [41]:
df = df.replace("Not Available", np.nan)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6450 entries, 0 to 6449
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Movie Name  6450 non-null   object
 1   Storyline   6178 non-null   object
dtypes: object(2)
memory usage: 100.9+ KB

In [44]:
df = df.dropna()

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6178 entries, 0 to 6449
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Movie Name  6178 non-null   object
 1   Storyline   6178 non-null   object
dtypes: object(2)
memory usage: 144.8+ KB

### Clean the text

In [52]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]
    return " ".join(tokens)

In [53]:
df["cleaned_storyline"] = df["Storyline"].apply(clean_text)
df.to_csv("cleaned_data.txt", sep="\t")

C:\Users\koushik\AppData\Local\Temp\ipykernel_8760\373804959.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["cleaned_storyline"] = df["Storyline"].apply(clean_text)

In [54]:
df.head()

,Movie Name,Storyline,cleaned_storyline
0,1. Fallout,"In a future, post-apocalyptic Los Angeles brou...",future post apocalyptic los angeles brought nu...
1,2. Cross,Series adaptation of James Patterson novels ab...,series adaptation james patterson novels compl...
2,3. Landman,A modern-day tale of fortune seeking in the wo...,modern day tale fortune seeking world west tex...
3,4. High Potential,A single mom with three kids helps solve an un...,single mom three kids helps solve unsolvable c...
4,5. The Substance,A fading celebrity takes a black-market drug: ...,fading celebrity takes black market drug cell ...

### Text Vectorization

In [56]:
vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1,2))
tfidf_matrix = vectorizer.fit_transform(df["cleaned_storyline"])

### Cosine Similarity

In [58]:
cosine_sim = cosine_similarity(tfidf_matrix)

### Hence the TASK 2 has been completed successfully!

## TASK 3: Recommendation System:
---
* ***Algorithm:*** Use Cosine Similarity or other ML algorithms to find the top 5 most similar movies based on a user’s input.
* ***User Input:*** Users will be able to input a movie storyline into the Streamlit app, and the system will output the top 5 recommended movies based on storyline similarity.

In [60]:
def recommend_movies(user_input, df, vectorizer, tfidf_matrix):
    cleaned_input = clean_text(user_input)
    input_vector = vectorizer.transform([cleaned_input])
    
    similarity_scores = cosine_similarity(input_vector, tfidf_matrix)
    
    top_indices = similarity_scores.argsort()[0][-5:][::-1]
    
    return df.iloc[top_indices][["Movie Name", "Storyline"]]

### Test the model

In [61]:
user_input = "A modern-day tale of fortune seeking in the world of West Texas oil rigs"
result = recommend_movies(user_input, df, vectorizer, tfidf_matrix)
result

,Movie Name,Storyline
2,3. Landman,A modern-day tale of fortune seeking in the wo...
1616,1617. Very Parivarik,A modern-day couple who manages to adjust to t...
2695,2696. Junction,Junction addresses the modern day opioid crisi...
3121,3122. Son's Will,A post-apocalyptic tale set in the west Balkan...
2036,2037. Persona 3 Reload,A modern day remake of Persona 3 (2006). A tea...

### Hence the project has been completed successfully! 🙏🏾😎😎